
clone_depth: 5

environment:
  SCCACHE_CACHE_SIZE: 320M
  SCCACHE_VERSION: 0.2.12
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:

    # MSVC 2019 x86-64 w/debug iterators
    - CC: VC2019
      PLATFORM: x86_amd64
      TARGET: sanitizer
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MAKE_TOOL: jom
      TARGET_CC: msvc

    # MSVC 2019 x86-64 preview
    - CC: VC2019p
      PLATFORM: x86_amd64
      TARGET: shared
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      MAKE_TOOL: jom
      TARGET_CC: msvc

    # MinGW GCC
    - CC: MinGW
      PLATFORM: x86_amd64
      TARGET: static
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MAKE_TOOL: mingw32-make
      TARGET_CC: gcc

install:
  - call src\scripts\ci\setup_appveyor.bat

build_script:
  - python src\scripts\ci_build.py --os=windows --cc=%TARGET_CC% --without-python3 --compiler-cache=sccache --make-tool=%MAKE_TOOL% --cpu=%PLATFORM% %EXTRA_FLAGS% %TARGET%

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - release-2

cache:
  - C:\Users\appveyor\AppData\Local\Mozilla\sccache\cache
